[package]
name = "wde-render"
version = "0.1.0"
edition = "2021"
description = "High-level rendering logic for WaterDropEngine."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
thiserror = "1.0"
wde-wgpu = { path = "../wgpu" }
serde = { version = "1.0", features = ["derive"] }
bytemuck = { version = "1.14", features = [ "derive" ] }
async-channel = "2.3"
tobj = "4.0"
noise = "0.9"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]

[dependencies.bevy]
version = "0.14"
default-features = false
features = [
    "multi_threaded",
    "bevy_asset",
    "bevy_winit",
]

[features]
default = []
watch = ["bevy/file_watcher"]
trace = ["bevy/trace_tracy_memory"]
